[package]
name = "candle-lora"
readme = "README.md"
authors = ["Eric Buehler"]
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
candle-core.workspace = true
candle-nn.workspace = true
either.workspace = true
thiserror.workspace = true
trc.workspace = true

[features]
cuda = ["candle-core/cuda", "candle-nn/cuda"]